theme: jekyll-theme-minimal
logo: avatar.jpg
title: ãƒãƒªã‚¦ã‚¹
description: ğŸ‡ªğŸ‡º European ğŸ‘” CEO @twostairs ğŸ’» Hacking #NLP/#AI & #FinTech ğŸ¯ Adventurer ğŸ’ #Minimalist â˜•ï¸ Amateur barista âœˆ Frequent flyer
show_downloads: "false"
google_analytics: UA-42605714-6
